# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472868c2617c850acc2be225df6f7ced9c172c3c68e310820f301812afb5225575f20b254cf92a7ed7c1fb3c63e3281368d7e50eb0d6f33879617228f9aefc4f

test:
  secret_key_base: ece823eb2fd694058d94ec7cfa04d14d7574514df9d93ebcf5c8d22e44d2290772816690300b7db8c405ae054246a330b1e272ce3c5741e9ffd2a7ba82c11af3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
